version: '3'
services:
  frontend:
    build: syedumer98488/frontend1.0
    container_name: frontend-container
    ports:
      - 6400:6400
    restart: always
  
  backend:
    build: syedumer98488/backend1.0
    container_name: backend-container 
    ports:
     - 7400:7400
    restart: always 

    depends_on:
      - backend